package br.com.starsoft.social.model.beans;
// Generated 28/04/2013 15:50:49 by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * Estado generated by hbm2java
 */
@Entity
public class Estado  implements java.io.Serializable {


    @Id
     private Integer id;
     private String nome;
     private String uf;
     private Integer pais;

    public Estado() {
    }

    public Estado(String nome, String uf, Integer pais) {
       this.nome = nome;
       this.uf = uf;
       this.pais = pais;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public Integer getPais() {
        return this.pais;
    }
    
    public void setPais(Integer pais) {
        this.pais = pais;
    }

    @Override
    public String toString() {
        return "Estado{" + "id=" + id + ", nome=" + nome + ", uf=" + uf + ", pais=" + pais + '}';
    }




}


