package br.com.starsoft.social.model.beans;
// Generated 28/04/2013 15:50:49 by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * Pais generated by hbm2java
 */
@Entity
public class Pais  implements java.io.Serializable {


    @Id
     private Integer id;
     private String nome;
     private String sigla;

    public Pais() {
    }

    public Pais(String nome, String sigla) {
       this.nome = nome;
       this.sigla = sigla;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }




}


